-- СГЕНЕРИРОВАНО scripts/build-seed.ts из tenants/*/business.json. Не редактируйте вручную.
-- Только демо-данные: студии в режиме preview, записи помечены is_demo.


-- ===== cleanart =====
insert into public.tenants (slug, mode, timezone, profile) values ('cleanart', 'preview', 'Europe/Minsk', '{"name":"КлинАрт","shortName":"КлинАрт","kind":"Автомойка · центр Минска","tagline":"Автомойка в центре, на Ленина, 27. Каждый день с 9 до 22","description":"Бесконтактная и комплексная мойка, химчистка салона, полировка. До шести машин одновременно и зал ожидания с Wi-Fi. Демо-версия сайта для студии: цены и длительность примерные, их владелец меняет в кабинете.","address":"г. Минск, ул. Ленина, 27","phone":"+375 44 788-55-00","accent":"#FF5C8A","cards":[{"title":"В центре","text":"Ленина, 27 — рядом с работой и делами."},{"title":"До 6 машин","text":"Принимаем одновременно, без долгого ожидания."},{"title":"Wi-Fi","text":"Зал ожидания, пока моем машину."}],"booking":{"bufferMin":10,"stepMin":30,"leadMin":60,"cancelHours":3,"horizonDays":30},"media":{"hero":"/t/cleanart/media/hero.svg","logo":"/t/cleanart/media/logo.svg"}}'::jsonb)
on conflict (slug) do update set profile = excluded.profile, timezone = excluded.timezone;
insert into public.resources (tenant_id, key, name, sort) values ((select id from public.tenants where slug = 'cleanart'), 'post-1', 'Пост 1', 0) on conflict (tenant_id, key) do update set name = excluded.name, sort = excluded.sort;
insert into public.resources (tenant_id, key, name, sort) values ((select id from public.tenants where slug = 'cleanart'), 'post-2', 'Пост 2', 1) on conflict (tenant_id, key) do update set name = excluded.name, sort = excluded.sort;
insert into public.resources (tenant_id, key, name, sort) values ((select id from public.tenants where slug = 'cleanart'), 'post-3', 'Пост 3', 2) on conflict (tenant_id, key) do update set name = excluded.name, sort = excluded.sort;
insert into public.services (tenant_id, key, name, description, price, duration_min, active, sort) values ((select id from public.tenants where slug = 'cleanart'), 'complex', 'Комплексная мойка', 'Кузов, салон, коврики, стёкла', 45, 60, true, 0)
on conflict (tenant_id, key) do update set name = excluded.name, description = excluded.description, price = excluded.price, duration_min = excluded.duration_min, active = excluded.active, sort = excluded.sort;
insert into public.services (tenant_id, key, name, description, price, duration_min, active, sort) values ((select id from public.tenants where slug = 'cleanart'), 'touchless', 'Бесконтактная мойка', 'Кузов и диски', 25, 30, true, 1)
on conflict (tenant_id, key) do update set name = excluded.name, description = excluded.description, price = excluded.price, duration_min = excluded.duration_min, active = excluded.active, sort = excluded.sort;
insert into public.services (tenant_id, key, name, description, price, duration_min, active, sort) values ((select id from public.tenants where slug = 'cleanart'), 'interior', 'Химчистка салона', 'Сиденья, ковры, пластик', 230, 300, true, 2)
on conflict (tenant_id, key) do update set name = excluded.name, description = excluded.description, price = excluded.price, duration_min = excluded.duration_min, active = excluded.active, sort = excluded.sort;
insert into public.services (tenant_id, key, name, description, price, duration_min, active, sort) values ((select id from public.tenants where slug = 'cleanart'), 'polish', 'Полировка кузова', 'Восстановительная', 400, 480, true, 3)
on conflict (tenant_id, key) do update set name = excluded.name, description = excluded.description, price = excluded.price, duration_min = excluded.duration_min, active = excluded.active, sort = excluded.sort;
insert into public.services (tenant_id, key, name, description, price, duration_min, active, sort) values ((select id from public.tenants where slug = 'cleanart'), 'engine', 'Мойка двигателя', 'С консервацией', 35, 40, true, 4)
on conflict (tenant_id, key) do update set name = excluded.name, description = excluded.description, price = excluded.price, duration_min = excluded.duration_min, active = excluded.active, sort = excluded.sort;
insert into public.working_hours (tenant_id, weekday, opens, closes) values ((select id from public.tenants where slug = 'cleanart'), 0, '09:00', '22:00') on conflict (tenant_id, weekday) do update set opens = excluded.opens, closes = excluded.closes;
insert into public.working_hours (tenant_id, weekday, opens, closes) values ((select id from public.tenants where slug = 'cleanart'), 1, '09:00', '22:00') on conflict (tenant_id, weekday) do update set opens = excluded.opens, closes = excluded.closes;
insert into public.working_hours (tenant_id, weekday, opens, closes) values ((select id from public.tenants where slug = 'cleanart'), 2, '09:00', '22:00') on conflict (tenant_id, weekday) do update set opens = excluded.opens, closes = excluded.closes;
insert into public.working_hours (tenant_id, weekday, opens, closes) values ((select id from public.tenants where slug = 'cleanart'), 3, '09:00', '22:00') on conflict (tenant_id, weekday) do update set opens = excluded.opens, closes = excluded.closes;
insert into public.working_hours (tenant_id, weekday, opens, closes) values ((select id from public.tenants where slug = 'cleanart'), 4, '09:00', '22:00') on conflict (tenant_id, weekday) do update set opens = excluded.opens, closes = excluded.closes;
insert into public.working_hours (tenant_id, weekday, opens, closes) values ((select id from public.tenants where slug = 'cleanart'), 5, '09:00', '22:00') on conflict (tenant_id, weekday) do update set opens = excluded.opens, closes = excluded.closes;
insert into public.working_hours (tenant_id, weekday, opens, closes) values ((select id from public.tenants where slug = 'cleanart'), 6, '09:00', '22:00') on conflict (tenant_id, weekday) do update set opens = excluded.opens, closes = excluded.closes;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'cleanart'), '2026-11-07', true, null, null, 'День Октябрьской революции', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'cleanart'), '2026-12-25', true, null, null, 'Рождество Христово (католическое)', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'cleanart'), '2027-01-01', true, null, null, 'Новый год', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'cleanart'), '2027-01-02', true, null, null, 'Новый год', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'cleanart'), '2027-01-07', true, null, null, 'Рождество Христово (православное)', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'cleanart'), '2027-03-08', true, null, null, 'День женщин', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'cleanart'), '2027-05-01', true, null, null, 'Праздник труда', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'cleanart'), '2027-05-09', true, null, null, 'День Победы', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'cleanart'), '2027-05-11', true, null, null, 'Радуница', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'cleanart'), '2027-07-03', true, null, null, 'День Независимости', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'cleanart'), '2027-11-07', true, null, null, 'День Октябрьской революции', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'cleanart'), '2027-12-25', true, null, null, 'Рождество Христово (католическое)', 'config') on conflict (tenant_id, day) do nothing;
insert into public.works (tenant_id, key, photo_url, caption, sort, source) values ((select id from public.tenants where slug = 'cleanart'), 'w1', '/t/cleanart/media/work-1.svg', 'Пена на кузове', 0, 'config') on conflict (tenant_id, key) do update set photo_url = excluded.photo_url, caption = excluded.caption, sort = excluded.sort;
insert into public.works (tenant_id, key, photo_url, caption, sort, source) values ((select id from public.tenants where slug = 'cleanart'), 'w2', '/t/cleanart/media/work-2.svg', 'Диски', 1, 'config') on conflict (tenant_id, key) do update set photo_url = excluded.photo_url, caption = excluded.caption, sort = excluded.sort;
insert into public.works (tenant_id, key, photo_url, caption, sort, source) values ((select id from public.tenants where slug = 'cleanart'), 'w3', '/t/cleanart/media/work-3.svg', 'Блеск после полировки', 2, 'config') on conflict (tenant_id, key) do update set photo_url = excluded.photo_url, caption = excluded.caption, sort = excluded.sort;

-- ===== detailing-room =====
insert into public.tenants (slug, mode, timezone, profile) values ('detailing-room', 'preview', 'Europe/Minsk', '{"name":"Detailing room","shortName":"Det. room","kind":"Автомойка · ЖК «Вершина», Минск","tagline":"Автомойка у дома на паркинге ЖК «Вершина»","description":"Мойка прямо на паркинге жилого комплекса: оставили машину — забрали чистой. Воскресенье — только по предварительной записи. Демо-версия сайта для студии: цены и длительность примерные, их владелец меняет в кабинете.","address":"г. Минск, ул. Маршала Лосика, 59, паркинг ЖК «Вершина»","phone":"+375 44 589-05-50","accent":"#3CC98A","cards":[{"title":"Рядом с домом","text":"Паркинг ЖК «Вершина», не нужно ехать через город."},{"title":"Один пост","text":"Ваша машина в работе одна, без очереди."},{"title":"Воскресенье","text":"Принимаем по записи."}],"booking":{"bufferMin":10,"stepMin":30,"leadMin":60,"cancelHours":3,"horizonDays":30},"media":{"hero":"/t/detailing-room/media/hero.svg","logo":"/t/detailing-room/media/logo.svg"}}'::jsonb)
on conflict (slug) do update set profile = excluded.profile, timezone = excluded.timezone;
insert into public.resources (tenant_id, key, name, sort) values ((select id from public.tenants where slug = 'detailing-room'), 'post-1', 'Пост', 0) on conflict (tenant_id, key) do update set name = excluded.name, sort = excluded.sort;
insert into public.services (tenant_id, key, name, description, price, duration_min, active, sort) values ((select id from public.tenants where slug = 'detailing-room'), 'complex', 'Комплексная мойка', 'Кузов, салон, коврики', 50, 60, true, 0)
on conflict (tenant_id, key) do update set name = excluded.name, description = excluded.description, price = excluded.price, duration_min = excluded.duration_min, active = excluded.active, sort = excluded.sort;
insert into public.services (tenant_id, key, name, description, price, duration_min, active, sort) values ((select id from public.tenants where slug = 'detailing-room'), 'express', 'Экспресс-мойка кузова', 'Бесконтактная, сушка', 30, 30, true, 1)
on conflict (tenant_id, key) do update set name = excluded.name, description = excluded.description, price = excluded.price, duration_min = excluded.duration_min, active = excluded.active, sort = excluded.sort;
insert into public.services (tenant_id, key, name, description, price, duration_min, active, sort) values ((select id from public.tenants where slug = 'detailing-room'), 'interior', 'Химчистка салона', 'Сиденья, ковры, пластик', 220, 300, true, 2)
on conflict (tenant_id, key) do update set name = excluded.name, description = excluded.description, price = excluded.price, duration_min = excluded.duration_min, active = excluded.active, sort = excluded.sort;
insert into public.services (tenant_id, key, name, description, price, duration_min, active, sort) values ((select id from public.tenants where slug = 'detailing-room'), 'engine', 'Мойка двигателя', 'С консервацией', 35, 40, true, 3)
on conflict (tenant_id, key) do update set name = excluded.name, description = excluded.description, price = excluded.price, duration_min = excluded.duration_min, active = excluded.active, sort = excluded.sort;
insert into public.working_hours (tenant_id, weekday, opens, closes) values ((select id from public.tenants where slug = 'detailing-room'), 0, '09:00', '20:00') on conflict (tenant_id, weekday) do update set opens = excluded.opens, closes = excluded.closes;
insert into public.working_hours (tenant_id, weekday, opens, closes) values ((select id from public.tenants where slug = 'detailing-room'), 1, '09:00', '20:00') on conflict (tenant_id, weekday) do update set opens = excluded.opens, closes = excluded.closes;
insert into public.working_hours (tenant_id, weekday, opens, closes) values ((select id from public.tenants where slug = 'detailing-room'), 2, '09:00', '20:00') on conflict (tenant_id, weekday) do update set opens = excluded.opens, closes = excluded.closes;
insert into public.working_hours (tenant_id, weekday, opens, closes) values ((select id from public.tenants where slug = 'detailing-room'), 3, '09:00', '20:00') on conflict (tenant_id, weekday) do update set opens = excluded.opens, closes = excluded.closes;
insert into public.working_hours (tenant_id, weekday, opens, closes) values ((select id from public.tenants where slug = 'detailing-room'), 4, '09:00', '20:00') on conflict (tenant_id, weekday) do update set opens = excluded.opens, closes = excluded.closes;
insert into public.working_hours (tenant_id, weekday, opens, closes) values ((select id from public.tenants where slug = 'detailing-room'), 5, '09:00', '20:00') on conflict (tenant_id, weekday) do update set opens = excluded.opens, closes = excluded.closes;
insert into public.working_hours (tenant_id, weekday, opens, closes) values ((select id from public.tenants where slug = 'detailing-room'), 6, '09:00', '20:00') on conflict (tenant_id, weekday) do update set opens = excluded.opens, closes = excluded.closes;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'detailing-room'), '2026-11-07', true, null, null, 'День Октябрьской революции', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'detailing-room'), '2026-12-25', true, null, null, 'Рождество Христово (католическое)', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'detailing-room'), '2027-01-01', true, null, null, 'Новый год', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'detailing-room'), '2027-01-02', true, null, null, 'Новый год', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'detailing-room'), '2027-01-07', true, null, null, 'Рождество Христово (православное)', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'detailing-room'), '2027-03-08', true, null, null, 'День женщин', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'detailing-room'), '2027-05-01', true, null, null, 'Праздник труда', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'detailing-room'), '2027-05-09', true, null, null, 'День Победы', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'detailing-room'), '2027-05-11', true, null, null, 'Радуница', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'detailing-room'), '2027-07-03', true, null, null, 'День Независимости', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'detailing-room'), '2027-11-07', true, null, null, 'День Октябрьской революции', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'detailing-room'), '2027-12-25', true, null, null, 'Рождество Христово (католическое)', 'config') on conflict (tenant_id, day) do nothing;
insert into public.works (tenant_id, key, photo_url, caption, sort, source) values ((select id from public.tenants where slug = 'detailing-room'), 'w1', '/t/detailing-room/media/work-1.svg', 'Пена на кузове', 0, 'config') on conflict (tenant_id, key) do update set photo_url = excluded.photo_url, caption = excluded.caption, sort = excluded.sort;
insert into public.works (tenant_id, key, photo_url, caption, sort, source) values ((select id from public.tenants where slug = 'detailing-room'), 'w2', '/t/detailing-room/media/work-2.svg', 'Чистый салон', 1, 'config') on conflict (tenant_id, key) do update set photo_url = excluded.photo_url, caption = excluded.caption, sort = excluded.sort;
insert into public.works (tenant_id, key, photo_url, caption, sort, source) values ((select id from public.tenants where slug = 'detailing-room'), 'w3', '/t/detailing-room/media/work-3.svg', 'Диски после мойки', 2, 'config') on conflict (tenant_id, key) do update set photo_url = excluded.photo_url, caption = excluded.caption, sort = excluded.sort;

-- ===== graphite =====
insert into public.tenants (slug, mode, timezone, profile) values ('graphite', 'preview', 'Europe/Minsk', '{"name":"GRAPHITE Detailing","shortName":"GRAPHITE","kind":"Детейлинг-студия · Минск","tagline":"Полировка, керамика и плёнка. Два поста, тёплый бокс, фотоотчёт","description":"Работаем с кузовом и салоном так, как с собственной машиной: свет для поиска дефектов, замеры толщины ЛКП, фотоотчёт до и после. Свободное время видно сразу.","address":"г. Минск, ул. Тимирязева, 65Б, бокс 12","phone":"+375 29 000-00-00","accent":"#4690FF","cards":[{"title":"Гарантия 2 года","text":"На керамику и плёнку. Фотоотчёт до и после в мессенджер."},{"title":"Один пост — одна машина","text":"Никакой очереди в общем зале: ваш автомобиль на своём посту."},{"title":"Оплата по факту","text":"Наличными, картой или через ЕРИП после приёмки работы."}],"booking":{"bufferMin":15,"stepMin":30,"leadMin":60,"cancelHours":4,"horizonDays":30},"media":{"hero":"/t/graphite/media/hero.svg","logo":"/t/graphite/media/logo.svg"}}'::jsonb)
on conflict (slug) do update set profile = excluded.profile, timezone = excluded.timezone;
insert into public.resources (tenant_id, key, name, sort) values ((select id from public.tenants where slug = 'graphite'), 'post-1', 'Пост 1', 0) on conflict (tenant_id, key) do update set name = excluded.name, sort = excluded.sort;
insert into public.resources (tenant_id, key, name, sort) values ((select id from public.tenants where slug = 'graphite'), 'post-2', 'Пост 2 (плёнка)', 1) on conflict (tenant_id, key) do update set name = excluded.name, sort = excluded.sort;
insert into public.services (tenant_id, key, name, description, price, duration_min, active, sort) values ((select id from public.tenants where slug = 'graphite'), 'wash', 'Детейлинг-мойка', 'Двухфазная мойка, диски, арки, сушка', 45.5, 90, true, 0)
on conflict (tenant_id, key) do update set name = excluded.name, description = excluded.description, price = excluded.price, duration_min = excluded.duration_min, active = excluded.active, sort = excluded.sort;
insert into public.services (tenant_id, key, name, description, price, duration_min, active, sort) values ((select id from public.tenants where slug = 'graphite'), 'interior', 'Химчистка салона', 'Сиденья, потолок, ковры, пластик', 250, 300, true, 1)
on conflict (tenant_id, key) do update set name = excluded.name, description = excluded.description, price = excluded.price, duration_min = excluded.duration_min, active = excluded.active, sort = excluded.sort;
insert into public.services (tenant_id, key, name, description, price, duration_min, active, sort) values ((select id from public.tenants where slug = 'graphite'), 'polish', 'Полировка кузова', 'Двухэтапная, убираем голограммы и мелкие царапины', 450, 600, true, 2)
on conflict (tenant_id, key) do update set name = excluded.name, description = excluded.description, price = excluded.price, duration_min = excluded.duration_min, active = excluded.active, sort = excluded.sort;
insert into public.services (tenant_id, key, name, description, price, duration_min, active, sort) values ((select id from public.tenants where slug = 'graphite'), 'ceramic', 'Керамическое покрытие', 'Подготовка, полировка, 2 слоя керамики. Машина у нас двое суток', 900, 2880, true, 3)
on conflict (tenant_id, key) do update set name = excluded.name, description = excluded.description, price = excluded.price, duration_min = excluded.duration_min, active = excluded.active, sort = excluded.sort;
insert into public.services (tenant_id, key, name, description, price, duration_min, active, sort) values ((select id from public.tenants where slug = 'graphite'), 'ppf', 'Плёнка на зоны риска', 'Капот, фары, бампер, зеркала. Только пост 2', 1200, 2880, true, 4)
on conflict (tenant_id, key) do update set name = excluded.name, description = excluded.description, price = excluded.price, duration_min = excluded.duration_min, active = excluded.active, sort = excluded.sort;
insert into public.service_resources (tenant_id, service_id, resource_id) select t.id, s.id, r.id from public.tenants t join public.services s on s.tenant_id = t.id and s.key = 'ppf' join public.resources r on r.tenant_id = t.id and r.key = 'post-2' where t.slug = 'graphite' on conflict do nothing;
insert into public.working_hours (tenant_id, weekday, opens, closes) values ((select id from public.tenants where slug = 'graphite'), 1, '09:00', '21:00') on conflict (tenant_id, weekday) do update set opens = excluded.opens, closes = excluded.closes;
insert into public.working_hours (tenant_id, weekday, opens, closes) values ((select id from public.tenants where slug = 'graphite'), 2, '09:00', '21:00') on conflict (tenant_id, weekday) do update set opens = excluded.opens, closes = excluded.closes;
insert into public.working_hours (tenant_id, weekday, opens, closes) values ((select id from public.tenants where slug = 'graphite'), 3, '09:00', '21:00') on conflict (tenant_id, weekday) do update set opens = excluded.opens, closes = excluded.closes;
insert into public.working_hours (tenant_id, weekday, opens, closes) values ((select id from public.tenants where slug = 'graphite'), 4, '09:00', '21:00') on conflict (tenant_id, weekday) do update set opens = excluded.opens, closes = excluded.closes;
insert into public.working_hours (tenant_id, weekday, opens, closes) values ((select id from public.tenants where slug = 'graphite'), 5, '09:00', '21:00') on conflict (tenant_id, weekday) do update set opens = excluded.opens, closes = excluded.closes;
insert into public.working_hours (tenant_id, weekday, opens, closes) values ((select id from public.tenants where slug = 'graphite'), 6, '10:00', '18:00') on conflict (tenant_id, weekday) do update set opens = excluded.opens, closes = excluded.closes;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'graphite'), '2026-11-07', true, null, null, 'День Октябрьской революции', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'graphite'), '2026-12-25', true, null, null, 'Рождество Христово (католическое)', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'graphite'), '2027-01-01', true, null, null, 'Новый год', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'graphite'), '2027-01-02', true, null, null, 'Новый год', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'graphite'), '2027-01-07', true, null, null, 'Рождество Христово (православное)', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'graphite'), '2027-03-08', true, null, null, 'День женщин', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'graphite'), '2027-05-01', true, null, null, 'Праздник труда', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'graphite'), '2027-05-09', true, null, null, 'День Победы', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'graphite'), '2027-05-11', true, null, null, 'Радуница', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'graphite'), '2027-07-03', true, null, null, 'День Независимости', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'graphite'), '2027-11-07', true, null, null, 'День Октябрьской революции', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'graphite'), '2027-12-25', true, null, null, 'Рождество Христово (католическое)', 'config') on conflict (tenant_id, day) do nothing;
insert into public.works (tenant_id, key, photo_url, caption, sort, source) values ((select id from public.tenants where slug = 'graphite'), 'w1', '/t/graphite/media/work-1.svg', 'Керамика на чёрном седане', 0, 'config') on conflict (tenant_id, key) do update set photo_url = excluded.photo_url, caption = excluded.caption, sort = excluded.sort;
insert into public.works (tenant_id, key, photo_url, caption, sort, source) values ((select id from public.tenants where slug = 'graphite'), 'w2', '/t/graphite/media/work-2.svg', 'Полировка капота: до и после', 1, 'config') on conflict (tenant_id, key) do update set photo_url = excluded.photo_url, caption = excluded.caption, sort = excluded.sort;
insert into public.works (tenant_id, key, photo_url, caption, sort, source) values ((select id from public.tenants where slug = 'graphite'), 'w3', '/t/graphite/media/work-3.svg', 'Химчистка светлого салона', 2, 'config') on conflict (tenant_id, key) do update set photo_url = excluded.photo_url, caption = excluded.caption, sort = excluded.sort;
insert into public.works (tenant_id, key, photo_url, caption, sort, source) values ((select id from public.tenants where slug = 'graphite'), 'w4', '/t/graphite/media/work-4.svg', 'Плёнка на фары и бампер', 3, 'config') on conflict (tenant_id, key) do update set photo_url = excluded.photo_url, caption = excluded.caption, sort = excluded.sort;
select public.admin_insert_demo_booking((select id from public.tenants where slug = 'graphite'), 'demo-0', 'wash', 'post-1', 1, '10:00', 'Демо: Андрей', '+375 29 000-00-01', 'Geely Coolray, белый', 'accepted', '[]'::jsonb);
select public.admin_insert_demo_booking((select id from public.tenants where slug = 'graphite'), 'demo-1', 'ceramic', 'post-2', 2, '09:00', 'Демо: Ольга', '+375 33 000-00-02', 'Volkswagen Tiguan', 'new', '[]'::jsonb);
select public.admin_insert_demo_booking((select id from public.tenants where slug = 'graphite'), 'demo-2', 'interior', 'post-1', -1, '11:00', 'Демо: Сергей', '+375 44 000-00-03', 'Toyota Camry', 'done', '[{"kind":"pay","amount":250,"method":"card"}]'::jsonb);

-- ===== moyka-trostenetskaya =====
insert into public.tenants (slug, mode, timezone, profile) values ('moyka-trostenetskaya', 'preview', 'Europe/Minsk', '{"name":"Автомойка на Тростенецкой","shortName":"Мойка Т8","kind":"Автомойка и детейлинг · Минск","tagline":"Бесконтактная мойка, химчистка и полировка. Работаем с 8:00 до 22:00","description":"Большая мойка на Тростенецкой, 8: несколько постов, зал ожидания, кофе и чай с собой. Мойка двигателя, химчистка, полировка. Демо-версия сайта для студии: цены и длительность примерные, их владелец меняет в кабинете.","address":"г. Минск, Тростенецкая ул., 8","phone":"+375 17 242-18-45","accent":"#F59E0B","cards":[{"title":"8:00–22:00","text":"Каждый день, удобно до и после работы."},{"title":"Без очереди","text":"Несколько постов, точное время по записи."},{"title":"Кафе","text":"Кофе и чай с собой, пока моем машину."}],"booking":{"bufferMin":10,"stepMin":30,"leadMin":60,"cancelHours":3,"horizonDays":30},"media":{"hero":"/t/moyka-trostenetskaya/media/hero.svg","logo":"/t/moyka-trostenetskaya/media/logo.svg"}}'::jsonb)
on conflict (slug) do update set profile = excluded.profile, timezone = excluded.timezone;
insert into public.resources (tenant_id, key, name, sort) values ((select id from public.tenants where slug = 'moyka-trostenetskaya'), 'post-1', 'Пост 1', 0) on conflict (tenant_id, key) do update set name = excluded.name, sort = excluded.sort;
insert into public.resources (tenant_id, key, name, sort) values ((select id from public.tenants where slug = 'moyka-trostenetskaya'), 'post-2', 'Пост 2', 1) on conflict (tenant_id, key) do update set name = excluded.name, sort = excluded.sort;
insert into public.resources (tenant_id, key, name, sort) values ((select id from public.tenants where slug = 'moyka-trostenetskaya'), 'post-3', 'Пост 3', 2) on conflict (tenant_id, key) do update set name = excluded.name, sort = excluded.sort;
insert into public.services (tenant_id, key, name, description, price, duration_min, active, sort) values ((select id from public.tenants where slug = 'moyka-trostenetskaya'), 'complex', 'Комплексная мойка', 'Кузов, салон, коврики, стёкла', 54, 60, true, 0)
on conflict (tenant_id, key) do update set name = excluded.name, description = excluded.description, price = excluded.price, duration_min = excluded.duration_min, active = excluded.active, sort = excluded.sort;
insert into public.services (tenant_id, key, name, description, price, duration_min, active, sort) values ((select id from public.tenants where slug = 'moyka-trostenetskaya'), 'touchless', 'Бесконтактная мойка', 'Кузов и диски', 30, 30, true, 1)
on conflict (tenant_id, key) do update set name = excluded.name, description = excluded.description, price = excluded.price, duration_min = excluded.duration_min, active = excluded.active, sort = excluded.sort;
insert into public.services (tenant_id, key, name, description, price, duration_min, active, sort) values ((select id from public.tenants where slug = 'moyka-trostenetskaya'), 'interior', 'Химчистка салона', 'Полная', 240, 300, true, 2)
on conflict (tenant_id, key) do update set name = excluded.name, description = excluded.description, price = excluded.price, duration_min = excluded.duration_min, active = excluded.active, sort = excluded.sort;
insert into public.services (tenant_id, key, name, description, price, duration_min, active, sort) values ((select id from public.tenants where slug = 'moyka-trostenetskaya'), 'polish', 'Полировка кузова', 'Восстановительная', 380, 480, true, 3)
on conflict (tenant_id, key) do update set name = excluded.name, description = excluded.description, price = excluded.price, duration_min = excluded.duration_min, active = excluded.active, sort = excluded.sort;
insert into public.services (tenant_id, key, name, description, price, duration_min, active, sort) values ((select id from public.tenants where slug = 'moyka-trostenetskaya'), 'engine', 'Мойка двигателя', 'С консервацией', 40, 40, true, 4)
on conflict (tenant_id, key) do update set name = excluded.name, description = excluded.description, price = excluded.price, duration_min = excluded.duration_min, active = excluded.active, sort = excluded.sort;
insert into public.working_hours (tenant_id, weekday, opens, closes) values ((select id from public.tenants where slug = 'moyka-trostenetskaya'), 0, '08:00', '22:00') on conflict (tenant_id, weekday) do update set opens = excluded.opens, closes = excluded.closes;
insert into public.working_hours (tenant_id, weekday, opens, closes) values ((select id from public.tenants where slug = 'moyka-trostenetskaya'), 1, '08:00', '22:00') on conflict (tenant_id, weekday) do update set opens = excluded.opens, closes = excluded.closes;
insert into public.working_hours (tenant_id, weekday, opens, closes) values ((select id from public.tenants where slug = 'moyka-trostenetskaya'), 2, '08:00', '22:00') on conflict (tenant_id, weekday) do update set opens = excluded.opens, closes = excluded.closes;
insert into public.working_hours (tenant_id, weekday, opens, closes) values ((select id from public.tenants where slug = 'moyka-trostenetskaya'), 3, '08:00', '22:00') on conflict (tenant_id, weekday) do update set opens = excluded.opens, closes = excluded.closes;
insert into public.working_hours (tenant_id, weekday, opens, closes) values ((select id from public.tenants where slug = 'moyka-trostenetskaya'), 4, '08:00', '22:00') on conflict (tenant_id, weekday) do update set opens = excluded.opens, closes = excluded.closes;
insert into public.working_hours (tenant_id, weekday, opens, closes) values ((select id from public.tenants where slug = 'moyka-trostenetskaya'), 5, '08:00', '22:00') on conflict (tenant_id, weekday) do update set opens = excluded.opens, closes = excluded.closes;
insert into public.working_hours (tenant_id, weekday, opens, closes) values ((select id from public.tenants where slug = 'moyka-trostenetskaya'), 6, '08:00', '22:00') on conflict (tenant_id, weekday) do update set opens = excluded.opens, closes = excluded.closes;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'moyka-trostenetskaya'), '2026-11-07', true, null, null, 'День Октябрьской революции', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'moyka-trostenetskaya'), '2026-12-25', true, null, null, 'Рождество Христово (католическое)', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'moyka-trostenetskaya'), '2027-01-01', true, null, null, 'Новый год', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'moyka-trostenetskaya'), '2027-01-02', true, null, null, 'Новый год', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'moyka-trostenetskaya'), '2027-01-07', true, null, null, 'Рождество Христово (православное)', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'moyka-trostenetskaya'), '2027-03-08', true, null, null, 'День женщин', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'moyka-trostenetskaya'), '2027-05-01', true, null, null, 'Праздник труда', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'moyka-trostenetskaya'), '2027-05-09', true, null, null, 'День Победы', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'moyka-trostenetskaya'), '2027-05-11', true, null, null, 'Радуница', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'moyka-trostenetskaya'), '2027-07-03', true, null, null, 'День Независимости', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'moyka-trostenetskaya'), '2027-11-07', true, null, null, 'День Октябрьской революции', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'moyka-trostenetskaya'), '2027-12-25', true, null, null, 'Рождество Христово (католическое)', 'config') on conflict (tenant_id, day) do nothing;
insert into public.works (tenant_id, key, photo_url, caption, sort, source) values ((select id from public.tenants where slug = 'moyka-trostenetskaya'), 'w1', '/t/moyka-trostenetskaya/media/work-1.svg', 'Бесконтактная мойка', 0, 'config') on conflict (tenant_id, key) do update set photo_url = excluded.photo_url, caption = excluded.caption, sort = excluded.sort;
insert into public.works (tenant_id, key, photo_url, caption, sort, source) values ((select id from public.tenants where slug = 'moyka-trostenetskaya'), 'w2', '/t/moyka-trostenetskaya/media/work-2.svg', 'Полировка', 1, 'config') on conflict (tenant_id, key) do update set photo_url = excluded.photo_url, caption = excluded.caption, sort = excluded.sort;
insert into public.works (tenant_id, key, photo_url, caption, sort, source) values ((select id from public.tenants where slug = 'moyka-trostenetskaya'), 'w3', '/t/moyka-trostenetskaya/media/work-3.svg', 'Химчистка', 2, 'config') on conflict (tenant_id, key) do update set photo_url = excluded.photo_url, caption = excluded.caption, sort = excluded.sort;

-- ===== nero =====
insert into public.tenants (slug, mode, timezone, profile) values ('nero', 'preview', 'Europe/Minsk', '{"name":"Nero Detailing","shortName":"Nero","kind":"Детейлинг-студия · Минск","tagline":"Детейлинг на Семашко: керамика, полировка, химчистка","description":"Детейлинг-студия с автоматическими воротами и удобным заездом. Полировка, керамика, химчистка, защита фар. Демо-версия сайта для студии: цены и длительность примерные, их владелец меняет в кабинете.","address":"г. Минск, ул. Семашко, 25а","phone":"+375 29 180-16-01","accent":"#2EC4B6","cards":[{"title":"Керамика","text":"Защита блеска до 2 лет."},{"title":"Удобный заезд","text":"Автоматические ворота, доступный вход."},{"title":"Оплата на месте","text":"Наличными после приёмки работы."}],"booking":{"bufferMin":10,"stepMin":30,"leadMin":60,"cancelHours":3,"horizonDays":30},"media":{"hero":"/t/nero/media/hero.svg","logo":"/t/nero/media/logo.svg"}}'::jsonb)
on conflict (slug) do update set profile = excluded.profile, timezone = excluded.timezone;
insert into public.resources (tenant_id, key, name, sort) values ((select id from public.tenants where slug = 'nero'), 'post-1', 'Пост 1', 0) on conflict (tenant_id, key) do update set name = excluded.name, sort = excluded.sort;
insert into public.services (tenant_id, key, name, description, price, duration_min, active, sort) values ((select id from public.tenants where slug = 'nero'), 'wash', 'Детейлинг-мойка', 'Двухфазная мойка, диски, сушка', 60, 90, true, 0)
on conflict (tenant_id, key) do update set name = excluded.name, description = excluded.description, price = excluded.price, duration_min = excluded.duration_min, active = excluded.active, sort = excluded.sort;
insert into public.services (tenant_id, key, name, description, price, duration_min, active, sort) values ((select id from public.tenants where slug = 'nero'), 'interior', 'Химчистка салона', 'Полная, с сушкой', 260, 300, true, 1)
on conflict (tenant_id, key) do update set name = excluded.name, description = excluded.description, price = excluded.price, duration_min = excluded.duration_min, active = excluded.active, sort = excluded.sort;
insert into public.services (tenant_id, key, name, description, price, duration_min, active, sort) values ((select id from public.tenants where slug = 'nero'), 'polish', 'Полировка кузова', 'Двухэтапная', 420, 480, true, 2)
on conflict (tenant_id, key) do update set name = excluded.name, description = excluded.description, price = excluded.price, duration_min = excluded.duration_min, active = excluded.active, sort = excluded.sort;
insert into public.services (tenant_id, key, name, description, price, duration_min, active, sort) values ((select id from public.tenants where slug = 'nero'), 'ceramic', 'Керамическое покрытие', 'Подготовка, полировка, керамика', 800, 1440, true, 3)
on conflict (tenant_id, key) do update set name = excluded.name, description = excluded.description, price = excluded.price, duration_min = excluded.duration_min, active = excluded.active, sort = excluded.sort;
insert into public.services (tenant_id, key, name, description, price, duration_min, active, sort) values ((select id from public.tenants where slug = 'nero'), 'lights', 'Плёнка на фары', 'Полиуретан, обе фары', 150, 120, true, 4)
on conflict (tenant_id, key) do update set name = excluded.name, description = excluded.description, price = excluded.price, duration_min = excluded.duration_min, active = excluded.active, sort = excluded.sort;
insert into public.working_hours (tenant_id, weekday, opens, closes) values ((select id from public.tenants where slug = 'nero'), 1, '09:00', '19:00') on conflict (tenant_id, weekday) do update set opens = excluded.opens, closes = excluded.closes;
insert into public.working_hours (tenant_id, weekday, opens, closes) values ((select id from public.tenants where slug = 'nero'), 2, '09:00', '19:00') on conflict (tenant_id, weekday) do update set opens = excluded.opens, closes = excluded.closes;
insert into public.working_hours (tenant_id, weekday, opens, closes) values ((select id from public.tenants where slug = 'nero'), 3, '09:00', '19:00') on conflict (tenant_id, weekday) do update set opens = excluded.opens, closes = excluded.closes;
insert into public.working_hours (tenant_id, weekday, opens, closes) values ((select id from public.tenants where slug = 'nero'), 4, '09:00', '19:00') on conflict (tenant_id, weekday) do update set opens = excluded.opens, closes = excluded.closes;
insert into public.working_hours (tenant_id, weekday, opens, closes) values ((select id from public.tenants where slug = 'nero'), 5, '09:00', '19:00') on conflict (tenant_id, weekday) do update set opens = excluded.opens, closes = excluded.closes;
insert into public.working_hours (tenant_id, weekday, opens, closes) values ((select id from public.tenants where slug = 'nero'), 6, '09:00', '19:00') on conflict (tenant_id, weekday) do update set opens = excluded.opens, closes = excluded.closes;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'nero'), '2026-11-07', true, null, null, 'День Октябрьской революции', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'nero'), '2026-12-25', true, null, null, 'Рождество Христово (католическое)', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'nero'), '2027-01-01', true, null, null, 'Новый год', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'nero'), '2027-01-02', true, null, null, 'Новый год', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'nero'), '2027-01-07', true, null, null, 'Рождество Христово (православное)', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'nero'), '2027-03-08', true, null, null, 'День женщин', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'nero'), '2027-05-01', true, null, null, 'Праздник труда', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'nero'), '2027-05-09', true, null, null, 'День Победы', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'nero'), '2027-05-11', true, null, null, 'Радуница', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'nero'), '2027-07-03', true, null, null, 'День Независимости', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'nero'), '2027-11-07', true, null, null, 'День Октябрьской революции', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'nero'), '2027-12-25', true, null, null, 'Рождество Христово (католическое)', 'config') on conflict (tenant_id, day) do nothing;
insert into public.works (tenant_id, key, photo_url, caption, sort, source) values ((select id from public.tenants where slug = 'nero'), 'w1', '/t/nero/media/work-1.svg', 'Полировка', 0, 'config') on conflict (tenant_id, key) do update set photo_url = excluded.photo_url, caption = excluded.caption, sort = excluded.sort;
insert into public.works (tenant_id, key, photo_url, caption, sort, source) values ((select id from public.tenants where slug = 'nero'), 'w2', '/t/nero/media/work-2.svg', 'Химчистка салона', 1, 'config') on conflict (tenant_id, key) do update set photo_url = excluded.photo_url, caption = excluded.caption, sort = excluded.sort;
insert into public.works (tenant_id, key, photo_url, caption, sort, source) values ((select id from public.tenants where slug = 'nero'), 'w3', '/t/nero/media/work-3.svg', 'Защита фар', 2, 'config') on conflict (tenant_id, key) do update set photo_url = excluded.photo_url, caption = excluded.caption, sort = excluded.sort;

-- ===== olimpik =====
insert into public.tenants (slug, mode, timezone, profile) values ('olimpik', 'preview', 'Europe/Minsk', '{"name":"Олимпик Детейлинг","shortName":"Олимпик","kind":"Детейлинг · Минск, Заводской район","tagline":"Мойка паром, химчистка и полировка. Тёплый бокс на два автомобиля","description":"Бережная мойка паром и бесконтактная мойка, химчистка салона, мойка двигателя и днища, полировка кузова. Пока машина в работе — зал ожидания и Wi-Fi. Демо-версия сайта для студии: цены и длительность примерные, их владелец меняет в кабинете.","address":"г. Минск, ул. Жилуновича, 7/7-1, 1 этаж","phone":"+375 29 314-57-77","accent":"#D9A83A","cards":[{"title":"Мойка паром","text":"Деликатно для кузова и салона, без лишней химии."},{"title":"Два поста","text":"В боксе одновременно не больше двух машин — без очереди."},{"title":"Зал ожидания","text":"Wi-Fi и кофе, пока идёт работа."}],"booking":{"bufferMin":10,"stepMin":30,"leadMin":60,"cancelHours":3,"horizonDays":30},"media":{"hero":"/t/olimpik/media/hero.svg","logo":"/t/olimpik/media/logo.svg"}}'::jsonb)
on conflict (slug) do update set profile = excluded.profile, timezone = excluded.timezone;
insert into public.resources (tenant_id, key, name, sort) values ((select id from public.tenants where slug = 'olimpik'), 'post-1', 'Пост 1', 0) on conflict (tenant_id, key) do update set name = excluded.name, sort = excluded.sort;
insert into public.resources (tenant_id, key, name, sort) values ((select id from public.tenants where slug = 'olimpik'), 'post-2', 'Пост 2', 1) on conflict (tenant_id, key) do update set name = excluded.name, sort = excluded.sort;
insert into public.services (tenant_id, key, name, description, price, duration_min, active, sort) values ((select id from public.tenants where slug = 'olimpik'), 'complex', 'Комплексная мойка', 'Кузов, салон, коврики, стёкла', 100, 90, true, 0)
on conflict (tenant_id, key) do update set name = excluded.name, description = excluded.description, price = excluded.price, duration_min = excluded.duration_min, active = excluded.active, sort = excluded.sort;
insert into public.services (tenant_id, key, name, description, price, duration_min, active, sort) values ((select id from public.tenants where slug = 'olimpik'), 'steam', 'Мойка паром', 'Кузов и диски паром, сушка', 60, 60, true, 1)
on conflict (tenant_id, key) do update set name = excluded.name, description = excluded.description, price = excluded.price, duration_min = excluded.duration_min, active = excluded.active, sort = excluded.sort;
insert into public.services (tenant_id, key, name, description, price, duration_min, active, sort) values ((select id from public.tenants where slug = 'olimpik'), 'interior', 'Химчистка салона', 'Сиденья, потолок, ковры, пластик', 280, 300, true, 2)
on conflict (tenant_id, key) do update set name = excluded.name, description = excluded.description, price = excluded.price, duration_min = excluded.duration_min, active = excluded.active, sort = excluded.sort;
insert into public.services (tenant_id, key, name, description, price, duration_min, active, sort) values ((select id from public.tenants where slug = 'olimpik'), 'polish', 'Полировка кузова', 'Восстановительная, двухэтапная', 450, 480, true, 3)
on conflict (tenant_id, key) do update set name = excluded.name, description = excluded.description, price = excluded.price, duration_min = excluded.duration_min, active = excluded.active, sort = excluded.sort;
insert into public.services (tenant_id, key, name, description, price, duration_min, active, sort) values ((select id from public.tenants where slug = 'olimpik'), 'engine', 'Мойка двигателя', 'Паром, с консервацией', 40, 45, true, 4)
on conflict (tenant_id, key) do update set name = excluded.name, description = excluded.description, price = excluded.price, duration_min = excluded.duration_min, active = excluded.active, sort = excluded.sort;
insert into public.services (tenant_id, key, name, description, price, duration_min, active, sort) values ((select id from public.tenants where slug = 'olimpik'), 'underbody', 'Мойка днища', 'Арки, днище, пороги', 35, 30, true, 5)
on conflict (tenant_id, key) do update set name = excluded.name, description = excluded.description, price = excluded.price, duration_min = excluded.duration_min, active = excluded.active, sort = excluded.sort;
insert into public.working_hours (tenant_id, weekday, opens, closes) values ((select id from public.tenants where slug = 'olimpik'), 0, '10:00', '20:00') on conflict (tenant_id, weekday) do update set opens = excluded.opens, closes = excluded.closes;
insert into public.working_hours (tenant_id, weekday, opens, closes) values ((select id from public.tenants where slug = 'olimpik'), 1, '10:00', '20:00') on conflict (tenant_id, weekday) do update set opens = excluded.opens, closes = excluded.closes;
insert into public.working_hours (tenant_id, weekday, opens, closes) values ((select id from public.tenants where slug = 'olimpik'), 2, '10:00', '20:00') on conflict (tenant_id, weekday) do update set opens = excluded.opens, closes = excluded.closes;
insert into public.working_hours (tenant_id, weekday, opens, closes) values ((select id from public.tenants where slug = 'olimpik'), 3, '10:00', '20:00') on conflict (tenant_id, weekday) do update set opens = excluded.opens, closes = excluded.closes;
insert into public.working_hours (tenant_id, weekday, opens, closes) values ((select id from public.tenants where slug = 'olimpik'), 4, '10:00', '20:00') on conflict (tenant_id, weekday) do update set opens = excluded.opens, closes = excluded.closes;
insert into public.working_hours (tenant_id, weekday, opens, closes) values ((select id from public.tenants where slug = 'olimpik'), 5, '10:00', '20:00') on conflict (tenant_id, weekday) do update set opens = excluded.opens, closes = excluded.closes;
insert into public.working_hours (tenant_id, weekday, opens, closes) values ((select id from public.tenants where slug = 'olimpik'), 6, '10:00', '20:00') on conflict (tenant_id, weekday) do update set opens = excluded.opens, closes = excluded.closes;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'olimpik'), '2026-11-07', true, null, null, 'День Октябрьской революции', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'olimpik'), '2026-12-25', true, null, null, 'Рождество Христово (католическое)', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'olimpik'), '2027-01-01', true, null, null, 'Новый год', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'olimpik'), '2027-01-02', true, null, null, 'Новый год', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'olimpik'), '2027-01-07', true, null, null, 'Рождество Христово (православное)', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'olimpik'), '2027-03-08', true, null, null, 'День женщин', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'olimpik'), '2027-05-01', true, null, null, 'Праздник труда', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'olimpik'), '2027-05-09', true, null, null, 'День Победы', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'olimpik'), '2027-05-11', true, null, null, 'Радуница', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'olimpik'), '2027-07-03', true, null, null, 'День Независимости', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'olimpik'), '2027-11-07', true, null, null, 'День Октябрьской революции', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'olimpik'), '2027-12-25', true, null, null, 'Рождество Христово (католическое)', 'config') on conflict (tenant_id, day) do nothing;
insert into public.works (tenant_id, key, photo_url, caption, sort, source) values ((select id from public.tenants where slug = 'olimpik'), 'w1', '/t/olimpik/media/work-1.svg', 'Полировка: глубокий блеск', 0, 'config') on conflict (tenant_id, key) do update set photo_url = excluded.photo_url, caption = excluded.caption, sort = excluded.sort;
insert into public.works (tenant_id, key, photo_url, caption, sort, source) values ((select id from public.tenants where slug = 'olimpik'), 'w2', '/t/olimpik/media/work-2.svg', 'Химчистка салона', 1, 'config') on conflict (tenant_id, key) do update set photo_url = excluded.photo_url, caption = excluded.caption, sort = excluded.sort;
insert into public.works (tenant_id, key, photo_url, caption, sort, source) values ((select id from public.tenants where slug = 'olimpik'), 'w3', '/t/olimpik/media/work-3.svg', 'Мойка паром', 2, 'config') on conflict (tenant_id, key) do update set photo_url = excluded.photo_url, caption = excluded.caption, sort = excluded.sort;

-- ===== protector =====
insert into public.tenants (slug, mode, timezone, profile) values ('protector', 'preview', 'Europe/Minsk', '{"name":"Шинный двор «Протектор»","shortName":"Протектор","kind":"Шиномонтаж · Брест","tagline":"Переобуем за 40 минут. Балансировка, ремонт проколов, хранение","description":"Три подъёмника и запись по минутам: приезжаете к своему времени и не стоите в очереди. Колёса до R22, низкий профиль и Run Flat.","address":"г. Брест, ул. Пример, 7","phone":"+375 33 000-00-00","accent":"#FF8A3D","cards":[{"title":"40 минут","text":"Средняя сезонная замена для легковой машины."},{"title":"До R22","text":"Низкий профиль, Run Flat, внедорожники."},{"title":"Хранение","text":"Сезонное хранение шин и дисков в тёплом складе."}],"booking":{"bufferMin":5,"stepMin":15,"leadMin":30,"cancelHours":1,"horizonDays":14},"media":{"hero":"/t/protector/media/hero.svg","logo":"/t/protector/media/logo.svg"}}'::jsonb)
on conflict (slug) do update set profile = excluded.profile, timezone = excluded.timezone;
insert into public.resources (tenant_id, key, name, sort) values ((select id from public.tenants where slug = 'protector'), 'lift-1', 'Подъёмник 1', 0) on conflict (tenant_id, key) do update set name = excluded.name, sort = excluded.sort;
insert into public.resources (tenant_id, key, name, sort) values ((select id from public.tenants where slug = 'protector'), 'lift-2', 'Подъёмник 2', 1) on conflict (tenant_id, key) do update set name = excluded.name, sort = excluded.sort;
insert into public.resources (tenant_id, key, name, sort) values ((select id from public.tenants where slug = 'protector'), 'lift-3', 'Подъёмник 3 (грузовые)', 2) on conflict (tenant_id, key) do update set name = excluded.name, sort = excluded.sort;
insert into public.services (tenant_id, key, name, description, price, duration_min, active, sort) values ((select id from public.tenants where slug = 'protector'), 'tires-small', 'Сезонная замена R13–R16', 'Снятие, монтаж, балансировка 4 колёс', 35, 45, true, 0)
on conflict (tenant_id, key) do update set name = excluded.name, description = excluded.description, price = excluded.price, duration_min = excluded.duration_min, active = excluded.active, sort = excluded.sort;
insert into public.service_resources (tenant_id, service_id, resource_id) select t.id, s.id, r.id from public.tenants t join public.services s on s.tenant_id = t.id and s.key = 'tires-small' join public.resources r on r.tenant_id = t.id and r.key = 'lift-1' where t.slug = 'protector' on conflict do nothing;
insert into public.service_resources (tenant_id, service_id, resource_id) select t.id, s.id, r.id from public.tenants t join public.services s on s.tenant_id = t.id and s.key = 'tires-small' join public.resources r on r.tenant_id = t.id and r.key = 'lift-2' where t.slug = 'protector' on conflict do nothing;
insert into public.services (tenant_id, key, name, description, price, duration_min, active, sort) values ((select id from public.tenants where slug = 'protector'), 'tires-big', 'Сезонная замена R17–R22', 'Снятие, монтаж, балансировка 4 колёс', 55, 60, true, 1)
on conflict (tenant_id, key) do update set name = excluded.name, description = excluded.description, price = excluded.price, duration_min = excluded.duration_min, active = excluded.active, sort = excluded.sort;
insert into public.services (tenant_id, key, name, description, price, duration_min, active, sort) values ((select id from public.tenants where slug = 'protector'), 'balance', 'Балансировка 4 колёс', '', 20, 30, true, 2)
on conflict (tenant_id, key) do update set name = excluded.name, description = excluded.description, price = excluded.price, duration_min = excluded.duration_min, active = excluded.active, sort = excluded.sort;
insert into public.services (tenant_id, key, name, description, price, duration_min, active, sort) values ((select id from public.tenants where slug = 'protector'), 'repair', 'Ремонт прокола', 'Жгут или грибок, одно колесо', 15, 30, true, 3)
on conflict (tenant_id, key) do update set name = excluded.name, description = excluded.description, price = excluded.price, duration_min = excluded.duration_min, active = excluded.active, sort = excluded.sort;
insert into public.working_hours (tenant_id, weekday, opens, closes) values ((select id from public.tenants where slug = 'protector'), 0, '09:00', '15:00') on conflict (tenant_id, weekday) do update set opens = excluded.opens, closes = excluded.closes;
insert into public.working_hours (tenant_id, weekday, opens, closes) values ((select id from public.tenants where slug = 'protector'), 1, '08:00', '20:00') on conflict (tenant_id, weekday) do update set opens = excluded.opens, closes = excluded.closes;
insert into public.working_hours (tenant_id, weekday, opens, closes) values ((select id from public.tenants where slug = 'protector'), 2, '08:00', '20:00') on conflict (tenant_id, weekday) do update set opens = excluded.opens, closes = excluded.closes;
insert into public.working_hours (tenant_id, weekday, opens, closes) values ((select id from public.tenants where slug = 'protector'), 3, '08:00', '20:00') on conflict (tenant_id, weekday) do update set opens = excluded.opens, closes = excluded.closes;
insert into public.working_hours (tenant_id, weekday, opens, closes) values ((select id from public.tenants where slug = 'protector'), 4, '08:00', '20:00') on conflict (tenant_id, weekday) do update set opens = excluded.opens, closes = excluded.closes;
insert into public.working_hours (tenant_id, weekday, opens, closes) values ((select id from public.tenants where slug = 'protector'), 5, '08:00', '20:00') on conflict (tenant_id, weekday) do update set opens = excluded.opens, closes = excluded.closes;
insert into public.working_hours (tenant_id, weekday, opens, closes) values ((select id from public.tenants where slug = 'protector'), 6, '09:00', '17:00') on conflict (tenant_id, weekday) do update set opens = excluded.opens, closes = excluded.closes;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'protector'), '2026-11-07', true, null, null, 'День Октябрьской революции', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'protector'), '2026-12-25', true, null, null, 'Рождество Христово (католическое)', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'protector'), '2027-01-01', true, null, null, 'Новый год', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'protector'), '2027-01-02', true, null, null, 'Новый год', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'protector'), '2027-01-07', true, null, null, 'Рождество Христово (православное)', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'protector'), '2027-03-08', true, null, null, 'День женщин', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'protector'), '2027-05-01', true, null, null, 'Праздник труда', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'protector'), '2027-05-09', true, null, null, 'День Победы', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'protector'), '2027-05-11', true, null, null, 'Радуница', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'protector'), '2027-07-03', true, null, null, 'День Независимости', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'protector'), '2027-11-07', true, null, null, 'День Октябрьской революции', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'protector'), '2027-12-25', true, null, null, 'Рождество Христово (католическое)', 'config') on conflict (tenant_id, day) do nothing;
insert into public.works (tenant_id, key, photo_url, caption, sort, source) values ((select id from public.tenants where slug = 'protector'), 'w1', '/t/protector/media/work-1.svg', 'Балансировка на стенде', 0, 'config') on conflict (tenant_id, key) do update set photo_url = excluded.photo_url, caption = excluded.caption, sort = excluded.sort;
insert into public.works (tenant_id, key, photo_url, caption, sort, source) values ((select id from public.tenants where slug = 'protector'), 'w2', '/t/protector/media/work-2.svg', 'Монтаж низкого профиля R20', 1, 'config') on conflict (tenant_id, key) do update set photo_url = excluded.photo_url, caption = excluded.caption, sort = excluded.sort;
insert into public.works (tenant_id, key, photo_url, caption, sort, source) values ((select id from public.tenants where slug = 'protector'), 'w3', '/t/protector/media/work-3.svg', 'Сезонное хранение', 2, 'config') on conflict (tenant_id, key) do update set photo_url = excluded.photo_url, caption = excluded.caption, sort = excluded.sort;
select public.admin_insert_demo_booking((select id from public.tenants where slug = 'protector'), 'demo-0', 'tires-small', 'lift-1', 1, '08:00', 'Демо: Виктор', '+375 29 000-00-11', 'Renault Logan', 'new', '[]'::jsonb);
select public.admin_insert_demo_booking((select id from public.tenants where slug = 'protector'), 'demo-1', 'tires-big', 'lift-3', 1, '08:00', 'Демо: Наталья', '+375 25 000-00-12', 'Kia Sportage', 'new', '[]'::jsonb);

-- ===== rd-detailing =====
insert into public.tenants (slug, mode, timezone, profile) values ('rd-detailing', 'preview', 'Europe/Minsk', '{"name":"RD Detailing","shortName":"RD","kind":"Детейлинг-студия · Минск","tagline":"Полировка, плёнка, кузовной ремонт и тюнинг","description":"Студия детейлинга на Дзержинского: полировка и защитные покрытия, оклейка плёнкой, локальный кузовной ремонт и тюнинг. Демо-версия сайта для студии: цены и длительность примерные, их владелец меняет в кабинете.","address":"г. Минск, пр-т Дзержинского, 1в к6","phone":"+375 29 144-00-99","accent":"#E5484D","cards":[{"title":"Плёнка","text":"Полиуретан на зоны риска и полностью."},{"title":"Кузовной ремонт","text":"Сколы, царапины, локальная покраска."},{"title":"Тюнинг","text":"Антихром, тонировка, детали."}],"booking":{"bufferMin":10,"stepMin":30,"leadMin":60,"cancelHours":3,"horizonDays":30},"media":{"hero":"/t/rd-detailing/media/hero.svg","logo":"/t/rd-detailing/media/logo.svg"}}'::jsonb)
on conflict (slug) do update set profile = excluded.profile, timezone = excluded.timezone;
insert into public.resources (tenant_id, key, name, sort) values ((select id from public.tenants where slug = 'rd-detailing'), 'post-1', 'Пост 1', 0) on conflict (tenant_id, key) do update set name = excluded.name, sort = excluded.sort;
insert into public.resources (tenant_id, key, name, sort) values ((select id from public.tenants where slug = 'rd-detailing'), 'post-2', 'Пост 2 (плёнка)', 1) on conflict (tenant_id, key) do update set name = excluded.name, sort = excluded.sort;
insert into public.services (tenant_id, key, name, description, price, duration_min, active, sort) values ((select id from public.tenants where slug = 'rd-detailing'), 'polish', 'Полировка кузова', 'Абразивная, в два этапа', 450, 480, true, 0)
on conflict (tenant_id, key) do update set name = excluded.name, description = excluded.description, price = excluded.price, duration_min = excluded.duration_min, active = excluded.active, sort = excluded.sort;
insert into public.services (tenant_id, key, name, description, price, duration_min, active, sort) values ((select id from public.tenants where slug = 'rd-detailing'), 'ppf-zones', 'Плёнка на зоны риска', 'Капот, фары, бампер, зеркала', 1100, 2880, true, 1)
on conflict (tenant_id, key) do update set name = excluded.name, description = excluded.description, price = excluded.price, duration_min = excluded.duration_min, active = excluded.active, sort = excluded.sort;
insert into public.service_resources (tenant_id, service_id, resource_id) select t.id, s.id, r.id from public.tenants t join public.services s on s.tenant_id = t.id and s.key = 'ppf-zones' join public.resources r on r.tenant_id = t.id and r.key = 'post-2' where t.slug = 'rd-detailing' on conflict do nothing;
insert into public.services (tenant_id, key, name, description, price, duration_min, active, sort) values ((select id from public.tenants where slug = 'rd-detailing'), 'chips', 'Ремонт сколов', 'Локально, подбор краски', 60, 120, true, 2)
on conflict (tenant_id, key) do update set name = excluded.name, description = excluded.description, price = excluded.price, duration_min = excluded.duration_min, active = excluded.active, sort = excluded.sort;
insert into public.services (tenant_id, key, name, description, price, duration_min, active, sort) values ((select id from public.tenants where slug = 'rd-detailing'), 'tint', 'Тонировка', 'Задняя полусфера', 200, 180, true, 3)
on conflict (tenant_id, key) do update set name = excluded.name, description = excluded.description, price = excluded.price, duration_min = excluded.duration_min, active = excluded.active, sort = excluded.sort;
insert into public.services (tenant_id, key, name, description, price, duration_min, active, sort) values ((select id from public.tenants where slug = 'rd-detailing'), 'antichrome', 'Антихром', 'Оклейка хрома плёнкой', 250, 300, true, 4)
on conflict (tenant_id, key) do update set name = excluded.name, description = excluded.description, price = excluded.price, duration_min = excluded.duration_min, active = excluded.active, sort = excluded.sort;
insert into public.service_resources (tenant_id, service_id, resource_id) select t.id, s.id, r.id from public.tenants t join public.services s on s.tenant_id = t.id and s.key = 'antichrome' join public.resources r on r.tenant_id = t.id and r.key = 'post-2' where t.slug = 'rd-detailing' on conflict do nothing;
insert into public.working_hours (tenant_id, weekday, opens, closes) values ((select id from public.tenants where slug = 'rd-detailing'), 1, '10:00', '20:00') on conflict (tenant_id, weekday) do update set opens = excluded.opens, closes = excluded.closes;
insert into public.working_hours (tenant_id, weekday, opens, closes) values ((select id from public.tenants where slug = 'rd-detailing'), 2, '10:00', '20:00') on conflict (tenant_id, weekday) do update set opens = excluded.opens, closes = excluded.closes;
insert into public.working_hours (tenant_id, weekday, opens, closes) values ((select id from public.tenants where slug = 'rd-detailing'), 3, '10:00', '20:00') on conflict (tenant_id, weekday) do update set opens = excluded.opens, closes = excluded.closes;
insert into public.working_hours (tenant_id, weekday, opens, closes) values ((select id from public.tenants where slug = 'rd-detailing'), 4, '10:00', '20:00') on conflict (tenant_id, weekday) do update set opens = excluded.opens, closes = excluded.closes;
insert into public.working_hours (tenant_id, weekday, opens, closes) values ((select id from public.tenants where slug = 'rd-detailing'), 5, '10:00', '20:00') on conflict (tenant_id, weekday) do update set opens = excluded.opens, closes = excluded.closes;
insert into public.working_hours (tenant_id, weekday, opens, closes) values ((select id from public.tenants where slug = 'rd-detailing'), 6, '10:00', '17:00') on conflict (tenant_id, weekday) do update set opens = excluded.opens, closes = excluded.closes;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'rd-detailing'), '2026-11-07', true, null, null, 'День Октябрьской революции', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'rd-detailing'), '2026-12-25', true, null, null, 'Рождество Христово (католическое)', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'rd-detailing'), '2027-01-01', true, null, null, 'Новый год', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'rd-detailing'), '2027-01-02', true, null, null, 'Новый год', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'rd-detailing'), '2027-01-07', true, null, null, 'Рождество Христово (православное)', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'rd-detailing'), '2027-03-08', true, null, null, 'День женщин', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'rd-detailing'), '2027-05-01', true, null, null, 'Праздник труда', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'rd-detailing'), '2027-05-09', true, null, null, 'День Победы', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'rd-detailing'), '2027-05-11', true, null, null, 'Радуница', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'rd-detailing'), '2027-07-03', true, null, null, 'День Независимости', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'rd-detailing'), '2027-11-07', true, null, null, 'День Октябрьской революции', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'rd-detailing'), '2027-12-25', true, null, null, 'Рождество Христово (католическое)', 'config') on conflict (tenant_id, day) do nothing;
insert into public.works (tenant_id, key, photo_url, caption, sort, source) values ((select id from public.tenants where slug = 'rd-detailing'), 'w1', '/t/rd-detailing/media/work-1.svg', 'Полировка кузова', 0, 'config') on conflict (tenant_id, key) do update set photo_url = excluded.photo_url, caption = excluded.caption, sort = excluded.sort;
insert into public.works (tenant_id, key, photo_url, caption, sort, source) values ((select id from public.tenants where slug = 'rd-detailing'), 'w2', '/t/rd-detailing/media/work-2.svg', 'Плёнка на фары', 1, 'config') on conflict (tenant_id, key) do update set photo_url = excluded.photo_url, caption = excluded.caption, sort = excluded.sort;
insert into public.works (tenant_id, key, photo_url, caption, sort, source) values ((select id from public.tenants where slug = 'rd-detailing'), 'w3', '/t/rd-detailing/media/work-3.svg', 'Детали и диски', 2, 'config') on conflict (tenant_id, key) do update set photo_url = excluded.photo_url, caption = excluded.caption, sort = excluded.sort;

-- ===== демо-владельцы (только локально) =====
do $$
declare s text; u uuid;
begin
  if not exists (select 1 from information_schema.columns where table_schema = 'auth' and table_name = 'users' and column_name = 'encrypted_password') then
    return;
  end if;
  foreach s in array array['cleanart', 'detailing-room', 'graphite', 'moyka-trostenetskaya', 'nero', 'olimpik', 'protector', 'rd-detailing'] loop
    u := md5('owner-' || s)::uuid;
    execute $q$insert into auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, created_at, updated_at, raw_app_meta_data, raw_user_meta_data)
      values ('00000000-0000-0000-0000-000000000000', $1, 'authenticated', 'authenticated', $2, crypt('demo-owner-pass', gen_salt('bf')), now(), now(), now(), '{"provider":"email","providers":["email"]}', '{}')
      on conflict (id) do nothing$q$ using u, 'owner@' || s || '.local';
    execute $q$insert into auth.identities (id, user_id, provider_id, identity_data, provider, created_at, updated_at, last_sign_in_at)
      values (gen_random_uuid(), $1, $1::text, jsonb_build_object('sub', $1::text, 'email', $2), 'email', now(), now(), now())
      on conflict do nothing$q$ using u, 'owner@' || s || '.local';
    insert into public.tenant_members (tenant_id, user_id) select id, u from public.tenants where slug = s on conflict do nothing;
  end loop;
end $$;
