-- СГЕНЕРИРОВАНО scripts/build-seed.ts из tenants/*/business.json. Не редактируйте вручную.
-- Только демо-данные: студии в режиме preview, записи помечены is_demo.


-- ===== graphite =====
insert into public.tenants (slug, mode, timezone, profile) values ('graphite', 'preview', 'Europe/Minsk', '{"name":"GRAPHITE Detailing","shortName":"GRAPHITE","kind":"Детейлинг-студия · Минск","tagline":"Полировка, керамика и плёнка. Два поста, тёплый бокс, фотоотчёт","description":"Работаем с кузовом и салоном так, как с собственной машиной: свет для поиска дефектов, замеры толщины ЛКП, фотоотчёт до и после. Свободное время видно сразу.","address":"г. Минск, ул. Тимирязева, 65Б, бокс 12","phone":"+375 29 000-00-00","accent":"#4690FF","cards":[{"title":"Гарантия 2 года","text":"На керамику и плёнку. Фотоотчёт до и после в мессенджер."},{"title":"Один пост — одна машина","text":"Никакой очереди в общем зале: ваш автомобиль на своём посту."},{"title":"Оплата по факту","text":"Наличными, картой или через ЕРИП после приёмки работы."}],"booking":{"bufferMin":15,"stepMin":30,"leadMin":60,"cancelHours":4,"horizonDays":30},"media":{"hero":"/t/graphite/media/hero.svg","logo":"/t/graphite/media/logo.svg"}}'::jsonb)
on conflict (slug) do update set profile = excluded.profile, timezone = excluded.timezone;
insert into public.resources (tenant_id, key, name, sort) values ((select id from public.tenants where slug = 'graphite'), 'post-1', 'Пост 1', 0) on conflict (tenant_id, key) do update set name = excluded.name, sort = excluded.sort;
insert into public.resources (tenant_id, key, name, sort) values ((select id from public.tenants where slug = 'graphite'), 'post-2', 'Пост 2 (плёнка)', 1) on conflict (tenant_id, key) do update set name = excluded.name, sort = excluded.sort;
insert into public.services (tenant_id, key, name, description, price, duration_min, active, sort) values ((select id from public.tenants where slug = 'graphite'), 'wash', 'Детейлинг-мойка', 'Двухфазная мойка, диски, арки, сушка', 45.5, 90, true, 0)
on conflict (tenant_id, key) do update set name = excluded.name, description = excluded.description, price = excluded.price, duration_min = excluded.duration_min, active = excluded.active, sort = excluded.sort;
insert into public.services (tenant_id, key, name, description, price, duration_min, active, sort) values ((select id from public.tenants where slug = 'graphite'), 'interior', 'Химчистка салона', 'Сиденья, потолок, ковры, пластик', 250, 300, true, 1)
on conflict (tenant_id, key) do update set name = excluded.name, description = excluded.description, price = excluded.price, duration_min = excluded.duration_min, active = excluded.active, sort = excluded.sort;
insert into public.services (tenant_id, key, name, description, price, duration_min, active, sort) values ((select id from public.tenants where slug = 'graphite'), 'polish', 'Полировка кузова', 'Двухэтапная, убираем голограммы и мелкие царапины', 450, 600, true, 2)
on conflict (tenant_id, key) do update set name = excluded.name, description = excluded.description, price = excluded.price, duration_min = excluded.duration_min, active = excluded.active, sort = excluded.sort;
insert into public.services (tenant_id, key, name, description, price, duration_min, active, sort) values ((select id from public.tenants where slug = 'graphite'), 'ceramic', 'Керамическое покрытие', 'Подготовка, полировка, 2 слоя керамики. Машина у нас двое суток', 900, 2880, true, 3)
on conflict (tenant_id, key) do update set name = excluded.name, description = excluded.description, price = excluded.price, duration_min = excluded.duration_min, active = excluded.active, sort = excluded.sort;
insert into public.services (tenant_id, key, name, description, price, duration_min, active, sort) values ((select id from public.tenants where slug = 'graphite'), 'ppf', 'Плёнка на зоны риска', 'Капот, фары, бампер, зеркала. Только пост 2', 1200, 2880, true, 4)
on conflict (tenant_id, key) do update set name = excluded.name, description = excluded.description, price = excluded.price, duration_min = excluded.duration_min, active = excluded.active, sort = excluded.sort;
insert into public.service_resources (tenant_id, service_id, resource_id) select t.id, s.id, r.id from public.tenants t join public.services s on s.tenant_id = t.id and s.key = 'ppf' join public.resources r on r.tenant_id = t.id and r.key = 'post-2' where t.slug = 'graphite' on conflict do nothing;
insert into public.working_hours (tenant_id, weekday, opens, closes) values ((select id from public.tenants where slug = 'graphite'), 1, '09:00', '21:00') on conflict (tenant_id, weekday) do update set opens = excluded.opens, closes = excluded.closes;
insert into public.working_hours (tenant_id, weekday, opens, closes) values ((select id from public.tenants where slug = 'graphite'), 2, '09:00', '21:00') on conflict (tenant_id, weekday) do update set opens = excluded.opens, closes = excluded.closes;
insert into public.working_hours (tenant_id, weekday, opens, closes) values ((select id from public.tenants where slug = 'graphite'), 3, '09:00', '21:00') on conflict (tenant_id, weekday) do update set opens = excluded.opens, closes = excluded.closes;
insert into public.working_hours (tenant_id, weekday, opens, closes) values ((select id from public.tenants where slug = 'graphite'), 4, '09:00', '21:00') on conflict (tenant_id, weekday) do update set opens = excluded.opens, closes = excluded.closes;
insert into public.working_hours (tenant_id, weekday, opens, closes) values ((select id from public.tenants where slug = 'graphite'), 5, '09:00', '21:00') on conflict (tenant_id, weekday) do update set opens = excluded.opens, closes = excluded.closes;
insert into public.working_hours (tenant_id, weekday, opens, closes) values ((select id from public.tenants where slug = 'graphite'), 6, '10:00', '18:00') on conflict (tenant_id, weekday) do update set opens = excluded.opens, closes = excluded.closes;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'graphite'), '2026-11-07', true, null, null, 'День Октябрьской революции', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'graphite'), '2026-12-25', true, null, null, 'Рождество Христово (католическое)', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'graphite'), '2027-01-01', true, null, null, 'Новый год', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'graphite'), '2027-01-02', true, null, null, 'Новый год', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'graphite'), '2027-01-07', true, null, null, 'Рождество Христово (православное)', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'graphite'), '2027-03-08', true, null, null, 'День женщин', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'graphite'), '2027-05-01', true, null, null, 'Праздник труда', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'graphite'), '2027-05-09', true, null, null, 'День Победы', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'graphite'), '2027-05-11', true, null, null, 'Радуница', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'graphite'), '2027-07-03', true, null, null, 'День Независимости', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'graphite'), '2027-11-07', true, null, null, 'День Октябрьской революции', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'graphite'), '2027-12-25', true, null, null, 'Рождество Христово (католическое)', 'config') on conflict (tenant_id, day) do nothing;
insert into public.works (tenant_id, key, photo_url, caption, sort, source) values ((select id from public.tenants where slug = 'graphite'), 'w1', '/t/graphite/media/work-1.svg', 'Керамика на чёрном седане', 0, 'config') on conflict (tenant_id, key) do update set photo_url = excluded.photo_url, caption = excluded.caption, sort = excluded.sort;
insert into public.works (tenant_id, key, photo_url, caption, sort, source) values ((select id from public.tenants where slug = 'graphite'), 'w2', '/t/graphite/media/work-2.svg', 'Полировка капота: до и после', 1, 'config') on conflict (tenant_id, key) do update set photo_url = excluded.photo_url, caption = excluded.caption, sort = excluded.sort;
insert into public.works (tenant_id, key, photo_url, caption, sort, source) values ((select id from public.tenants where slug = 'graphite'), 'w3', '/t/graphite/media/work-3.svg', 'Химчистка светлого салона', 2, 'config') on conflict (tenant_id, key) do update set photo_url = excluded.photo_url, caption = excluded.caption, sort = excluded.sort;
insert into public.works (tenant_id, key, photo_url, caption, sort, source) values ((select id from public.tenants where slug = 'graphite'), 'w4', '/t/graphite/media/work-4.svg', 'Плёнка на фары и бампер', 3, 'config') on conflict (tenant_id, key) do update set photo_url = excluded.photo_url, caption = excluded.caption, sort = excluded.sort;
select public.admin_insert_demo_booking((select id from public.tenants where slug = 'graphite'), 'demo-0', 'wash', 'post-1', 1, '10:00', 'Демо: Андрей', '+375 29 000-00-01', 'Geely Coolray, белый', 'accepted', '[]'::jsonb);
select public.admin_insert_demo_booking((select id from public.tenants where slug = 'graphite'), 'demo-1', 'ceramic', 'post-2', 2, '09:00', 'Демо: Ольга', '+375 33 000-00-02', 'Volkswagen Tiguan', 'new', '[]'::jsonb);
select public.admin_insert_demo_booking((select id from public.tenants where slug = 'graphite'), 'demo-2', 'interior', 'post-1', -1, '11:00', 'Демо: Сергей', '+375 44 000-00-03', 'Toyota Camry', 'done', '[{"kind":"pay","amount":250,"method":"card"}]'::jsonb);

-- ===== protector =====
insert into public.tenants (slug, mode, timezone, profile) values ('protector', 'preview', 'Europe/Minsk', '{"name":"Шинный двор «Протектор»","shortName":"Протектор","kind":"Шиномонтаж · Брест","tagline":"Переобуем за 40 минут. Балансировка, ремонт проколов, хранение","description":"Три подъёмника и запись по минутам: приезжаете к своему времени и не стоите в очереди. Колёса до R22, низкий профиль и Run Flat.","address":"г. Брест, ул. Пример, 7","phone":"+375 33 000-00-00","accent":"#FF8A3D","cards":[{"title":"40 минут","text":"Средняя сезонная замена для легковой машины."},{"title":"До R22","text":"Низкий профиль, Run Flat, внедорожники."},{"title":"Хранение","text":"Сезонное хранение шин и дисков в тёплом складе."}],"booking":{"bufferMin":5,"stepMin":15,"leadMin":30,"cancelHours":1,"horizonDays":14},"media":{"hero":"/t/protector/media/hero.svg","logo":"/t/protector/media/logo.svg"}}'::jsonb)
on conflict (slug) do update set profile = excluded.profile, timezone = excluded.timezone;
insert into public.resources (tenant_id, key, name, sort) values ((select id from public.tenants where slug = 'protector'), 'lift-1', 'Подъёмник 1', 0) on conflict (tenant_id, key) do update set name = excluded.name, sort = excluded.sort;
insert into public.resources (tenant_id, key, name, sort) values ((select id from public.tenants where slug = 'protector'), 'lift-2', 'Подъёмник 2', 1) on conflict (tenant_id, key) do update set name = excluded.name, sort = excluded.sort;
insert into public.resources (tenant_id, key, name, sort) values ((select id from public.tenants where slug = 'protector'), 'lift-3', 'Подъёмник 3 (грузовые)', 2) on conflict (tenant_id, key) do update set name = excluded.name, sort = excluded.sort;
insert into public.services (tenant_id, key, name, description, price, duration_min, active, sort) values ((select id from public.tenants where slug = 'protector'), 'tires-small', 'Сезонная замена R13–R16', 'Снятие, монтаж, балансировка 4 колёс', 35, 45, true, 0)
on conflict (tenant_id, key) do update set name = excluded.name, description = excluded.description, price = excluded.price, duration_min = excluded.duration_min, active = excluded.active, sort = excluded.sort;
insert into public.service_resources (tenant_id, service_id, resource_id) select t.id, s.id, r.id from public.tenants t join public.services s on s.tenant_id = t.id and s.key = 'tires-small' join public.resources r on r.tenant_id = t.id and r.key = 'lift-1' where t.slug = 'protector' on conflict do nothing;
insert into public.service_resources (tenant_id, service_id, resource_id) select t.id, s.id, r.id from public.tenants t join public.services s on s.tenant_id = t.id and s.key = 'tires-small' join public.resources r on r.tenant_id = t.id and r.key = 'lift-2' where t.slug = 'protector' on conflict do nothing;
insert into public.services (tenant_id, key, name, description, price, duration_min, active, sort) values ((select id from public.tenants where slug = 'protector'), 'tires-big', 'Сезонная замена R17–R22', 'Снятие, монтаж, балансировка 4 колёс', 55, 60, true, 1)
on conflict (tenant_id, key) do update set name = excluded.name, description = excluded.description, price = excluded.price, duration_min = excluded.duration_min, active = excluded.active, sort = excluded.sort;
insert into public.services (tenant_id, key, name, description, price, duration_min, active, sort) values ((select id from public.tenants where slug = 'protector'), 'balance', 'Балансировка 4 колёс', '', 20, 30, true, 2)
on conflict (tenant_id, key) do update set name = excluded.name, description = excluded.description, price = excluded.price, duration_min = excluded.duration_min, active = excluded.active, sort = excluded.sort;
insert into public.services (tenant_id, key, name, description, price, duration_min, active, sort) values ((select id from public.tenants where slug = 'protector'), 'repair', 'Ремонт прокола', 'Жгут или грибок, одно колесо', 15, 30, true, 3)
on conflict (tenant_id, key) do update set name = excluded.name, description = excluded.description, price = excluded.price, duration_min = excluded.duration_min, active = excluded.active, sort = excluded.sort;
insert into public.working_hours (tenant_id, weekday, opens, closes) values ((select id from public.tenants where slug = 'protector'), 0, '09:00', '15:00') on conflict (tenant_id, weekday) do update set opens = excluded.opens, closes = excluded.closes;
insert into public.working_hours (tenant_id, weekday, opens, closes) values ((select id from public.tenants where slug = 'protector'), 1, '08:00', '20:00') on conflict (tenant_id, weekday) do update set opens = excluded.opens, closes = excluded.closes;
insert into public.working_hours (tenant_id, weekday, opens, closes) values ((select id from public.tenants where slug = 'protector'), 2, '08:00', '20:00') on conflict (tenant_id, weekday) do update set opens = excluded.opens, closes = excluded.closes;
insert into public.working_hours (tenant_id, weekday, opens, closes) values ((select id from public.tenants where slug = 'protector'), 3, '08:00', '20:00') on conflict (tenant_id, weekday) do update set opens = excluded.opens, closes = excluded.closes;
insert into public.working_hours (tenant_id, weekday, opens, closes) values ((select id from public.tenants where slug = 'protector'), 4, '08:00', '20:00') on conflict (tenant_id, weekday) do update set opens = excluded.opens, closes = excluded.closes;
insert into public.working_hours (tenant_id, weekday, opens, closes) values ((select id from public.tenants where slug = 'protector'), 5, '08:00', '20:00') on conflict (tenant_id, weekday) do update set opens = excluded.opens, closes = excluded.closes;
insert into public.working_hours (tenant_id, weekday, opens, closes) values ((select id from public.tenants where slug = 'protector'), 6, '09:00', '17:00') on conflict (tenant_id, weekday) do update set opens = excluded.opens, closes = excluded.closes;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'protector'), '2026-11-07', true, null, null, 'День Октябрьской революции', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'protector'), '2026-12-25', true, null, null, 'Рождество Христово (католическое)', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'protector'), '2027-01-01', true, null, null, 'Новый год', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'protector'), '2027-01-02', true, null, null, 'Новый год', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'protector'), '2027-01-07', true, null, null, 'Рождество Христово (православное)', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'protector'), '2027-03-08', true, null, null, 'День женщин', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'protector'), '2027-05-01', true, null, null, 'Праздник труда', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'protector'), '2027-05-09', true, null, null, 'День Победы', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'protector'), '2027-05-11', true, null, null, 'Радуница', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'protector'), '2027-07-03', true, null, null, 'День Независимости', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'protector'), '2027-11-07', true, null, null, 'День Октябрьской революции', 'config') on conflict (tenant_id, day) do nothing;
insert into public.schedule_exceptions (tenant_id, day, closed, opens, closes, note, source) values ((select id from public.tenants where slug = 'protector'), '2027-12-25', true, null, null, 'Рождество Христово (католическое)', 'config') on conflict (tenant_id, day) do nothing;
insert into public.works (tenant_id, key, photo_url, caption, sort, source) values ((select id from public.tenants where slug = 'protector'), 'w1', '/t/protector/media/work-1.svg', 'Балансировка на стенде', 0, 'config') on conflict (tenant_id, key) do update set photo_url = excluded.photo_url, caption = excluded.caption, sort = excluded.sort;
insert into public.works (tenant_id, key, photo_url, caption, sort, source) values ((select id from public.tenants where slug = 'protector'), 'w2', '/t/protector/media/work-2.svg', 'Монтаж низкого профиля R20', 1, 'config') on conflict (tenant_id, key) do update set photo_url = excluded.photo_url, caption = excluded.caption, sort = excluded.sort;
insert into public.works (tenant_id, key, photo_url, caption, sort, source) values ((select id from public.tenants where slug = 'protector'), 'w3', '/t/protector/media/work-3.svg', 'Сезонное хранение', 2, 'config') on conflict (tenant_id, key) do update set photo_url = excluded.photo_url, caption = excluded.caption, sort = excluded.sort;
select public.admin_insert_demo_booking((select id from public.tenants where slug = 'protector'), 'demo-0', 'tires-small', 'lift-1', 1, '08:00', 'Демо: Виктор', '+375 29 000-00-11', 'Renault Logan', 'new', '[]'::jsonb);
select public.admin_insert_demo_booking((select id from public.tenants where slug = 'protector'), 'demo-1', 'tires-big', 'lift-3', 1, '08:00', 'Демо: Наталья', '+375 25 000-00-12', 'Kia Sportage', 'new', '[]'::jsonb);

-- ===== демо-владельцы (только локально) =====
do $$
declare s text; u uuid;
begin
  if not exists (select 1 from information_schema.columns where table_schema = 'auth' and table_name = 'users' and column_name = 'encrypted_password') then
    return;
  end if;
  foreach s in array array['graphite', 'protector'] loop
    u := md5('owner-' || s)::uuid;
    execute $q$insert into auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, created_at, updated_at, raw_app_meta_data, raw_user_meta_data)
      values ('00000000-0000-0000-0000-000000000000', $1, 'authenticated', 'authenticated', $2, crypt('demo-owner-pass', gen_salt('bf')), now(), now(), now(), '{"provider":"email","providers":["email"]}', '{}')
      on conflict (id) do nothing$q$ using u, 'owner@' || s || '.local';
    execute $q$insert into auth.identities (id, user_id, provider_id, identity_data, provider, created_at, updated_at, last_sign_in_at)
      values (gen_random_uuid(), $1, $1::text, jsonb_build_object('sub', $1::text, 'email', $2), 'email', now(), now(), now())
      on conflict do nothing$q$ using u, 'owner@' || s || '.local';
    insert into public.tenant_members (tenant_id, user_id) select id, u from public.tenants where slug = s on conflict do nothing;
  end loop;
end $$;
